### ISSUE TITLE
normalization can be "unproductive" -- make it inductive?

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/a-mir-formality#68]
So the current solver treats all predicates as coinductive in a-mir-formality right now. I think this is (ultimately, RFC required) the right call for trait matching, but for associated type normalization -- at least as current managed -- it is not sound. Consider:

```
trait Foo { type FooItem; }
trait Bar { type BarItem; }

impl Foo for () {
    type FooItem = <() as Bar>::BarItem;
}

impl Bar for () {
    type BarItem = <() as Foo>::FooItem;
}
```

Now imagine that we have a goal like

```
forall<T> { normalizes-to(<() as Foo>::FooItem, T) }
```

This ought not to be provable -- you can't normalize `FooItem` to *any type `T`*. But it is provable if we are naively coinductive, because you get

* `normalizes-to(<() as Foo>::FooItem, T)` if
* `normalizes-to(<() as Bar>::BarItem, T)` if
* `normalizes-to(<() as Foo>::FooItem, T)` -- cycle, ok!

**Comment by nikomatsakis** [comment]
The simplest solution is to say that some predicates (notably, `normalizes-to`) are inductive. The solver already is "geared up" for this. There is a [`Prove/Coinductive`](https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/logic/grammar.rkt#L172) parameter that is either `+` or `-` to indicate coinductive (`+`) or inductive (`-`), but right now for predicates it is hard-coded to `+`:

https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/logic/cosld-solve/prove.rkt#L51

The logic layer doesn't really understand predicates, be could modify the `is-predicate` callback in the logic layer hook so that, instead of returning a boolean, it returns something like `(+ or - or not-predicate)`. Maybe we can merge `is-predicate` and `is-relation` (extended in #67 to include `is-builtin-predicate`):

https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/logic/hook.rkt#L29-L30

...to something like `classify-goal` that returns back a type like...

```
(Prove/GoalClassification ::=
    (is-predicate Prove/Coinductive)
    is-builtin-predicate
    is-relation
    other-goal
    )
```

...we'd also have to remove the [`is-predicate` and `is-relation` metafunctions that invoke the hook](https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/logic/hook.rkt#L89-L100) and replace them with a similar one called `classify-goal`. 

We'd have to change the code that invokes the `is-predicate` metafunctions. e.g. where the solver does

https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/logic/cosld-solve/prove.rkt#L48-L54

it would instead do `(where (is-predicate Prove/Coinductive) (classify-goal Predicate))` (and then pass `Prove/Coinductive` instead of `+` to `clause-proves`).

Finally, we'd have to modify the places that create hooks:

* [the logic test hook](https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/logic/test/hook.rkt#L12-L28), used for testing the logic layer in isolation
* [the ty test hook](https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/ty/test/hook.rkt#L26-L44), used for testing the type/logic layer in isolation
* [the `formality-decl-hook` function](https://github.com/nikomatsakis/a-mir-formality/blob/ba99afa9aeb45bbfeda498d22b53c50e77c82c59/src/decl/decl-to-clause.rkt#L47-L77), which makes the "real" hook used from that point forward

**Comment by nikomatsakis** [comment]
Of course, to close this PR properly, I would start by creating a test that shows the unsoundness in action.

**Comment by voidc** [comment]
I created a test to confirm the suspected unsoundness but the goal as stated above turned out to not be provable.
My test: https://github.com/voidc/a-mir-formality/commit/a9ac3fc27c579772a9435bc702bc8b466110dbdf
